'use client';

import { useEffect, useState } from 'react';
import { Plus, RefreshCw, ToggleLeft, ToggleRight } from 'lucide-react';

const TYPES = ['motorcycle','sedan','suv','truck'];
const SIZES = ['small','medium','large','xl','xxl'];
const PLATFORMS = ['Grab','Foodpanda','JoyRide','Maxim','inDrive','SPX Express','J&T Express'];

export default function PromosPage() {
  const [promos,setPromos]=useState<any[]>([]); const [show,setShow]=useState(false); const [loading,setLoading]=useState(true);
  const [form,setForm]=useState<any>({name:'',description:'',discountType:'percentage',discountValue:20,eligibleVehicleTypes:[...TYPES],eligibleVehicleSizes:[...SIZES],eligiblePlatforms:[...PLATFORMS],requiresVerification:false,active:true});
  const load=async()=>{setLoading(true);try{const r=await fetch('/api/promos',{cache:'no-store'});const d=await r.json();if(d.success)setPromos(d.promos||[]);}finally{setLoading(false)}};
  useEffect(()=>{load()},[]);
  const toggle=(key:string,value:string)=>setForm((f:any)=>({...f,[key]:f[key].includes(value)?f[key].filter((x:string)=>x!==value):[...f[key],value]}));
  const save=async()=>{const r=await fetch('/api/promos',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const d=await r.json();if(!r.ok) return alert(d.error||'Unable to save promo');setShow(false);setForm({name:'',description:'',discountType:'percentage',discountValue:20,eligibleVehicleTypes:[...TYPES],eligibleVehicleSizes:[...SIZES],eligiblePlatforms:[...PLATFORMS],requiresVerification:false,active:true});load()};
  return <div className="min-h-full overflow-y-auto bg-slate-50/60 p-6 text-slate-900"><div className="mx-auto max-w-6xl space-y-5"><div className="flex items-center justify-between rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div><h1 className="text-lg font-black">Promos & Discounts</h1><p className="text-xs text-slate-500">Configure eligibility without changing the POS code.</p></div><div className="flex gap-2"><button onClick={load} className="rounded-xl border p-2.5"><RefreshCw className={`h-4 w-4 ${loading?'animate-spin':''}`}/></button><button onClick={()=>setShow(true)} className="flex items-center gap-2 rounded-xl bg-slate-900 px-4 py-2.5 text-xs font-bold text-white"><Plus className="h-4 w-4"/> New Promo</button></div></div>
  <div className="grid gap-4 md:grid-cols-2">{promos.map(p=><div key={p._id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex justify-between"><div><h2 className="text-sm font-black">{p.name}</h2><p className="mt-1 text-xs text-slate-500">{p.description}</p></div>{p.active?<ToggleRight className="text-emerald-600"/>:<ToggleLeft className="text-slate-400"/>}</div><div className="mt-4 text-xl font-black">{p.discountType==='percentage'?`${p.discountValue}% OFF`:`₱${Number(p.discountValue).toLocaleString()}`}</div><div className="mt-3 space-y-1 text-[10px] text-slate-500"><p><b>Vehicles:</b> {p.eligibleVehicleTypes?.join(', ')||'None'}</p><p><b>Sizes:</b> {p.eligibleVehicleSizes?.join(', ')||'None'}</p><p><b>Platforms:</b> {p.eligiblePlatforms?.join(', ')||'None'}</p><p><b>Verification:</b> {p.requiresVerification?'Required':'Not required'}</p></div></div>)}</div>
  {show&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/40 p-4"><div className="max-h-[90vh] w-full max-w-lg overflow-y-auto rounded-2xl bg-white p-5 shadow-xl"><div className="flex justify-between"><h2 className="text-sm font-black">New Promotion</h2><button onClick={()=>setShow(false)}>✕</button></div><div className="mt-4 space-y-4"><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Promo name" className="w-full rounded-xl border p-3 text-xs"/><textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Description" className="w-full rounded-xl border p-3 text-xs"/><div className="grid grid-cols-2 gap-3"><select value={form.discountType} onChange={e=>setForm({...form,discountType:e.target.value})} className="rounded-xl border p-3 text-xs"><option value="percentage">Percentage</option><option value="fixed">Fixed amount</option></select><input type="number" value={form.discountValue} onChange={e=>setForm({...form,discountValue:Number(e.target.value)})} className="rounded-xl border p-3 text-xs"/></div><Group title="Vehicle types" values={TYPES} selected={form.eligibleVehicleTypes} onToggle={(v:string)=>toggle('eligibleVehicleTypes',v)}/><Group title="Vehicle sizes" values={SIZES} selected={form.eligibleVehicleSizes} onToggle={(v:string)=>toggle('eligibleVehicleSizes',v)}/><Group title="Rider platforms" values={PLATFORMS} selected={form.eligiblePlatforms} onToggle={(v:string)=>toggle('eligiblePlatforms',v)}/><label className="flex items-center gap-2 text-xs font-bold"><input type="checkbox" checked={form.requiresVerification} onChange={e=>setForm({...form,requiresVerification:e.target.checked})}/> Require verification</label><button onClick={save} className="w-full rounded-xl bg-blue-600 py-3 text-xs font-black text-white">Create Promo</button></div></div></div>}
  </div></div>
}
function Group({title,values,selected,onToggle}:{title:string;values:string[];selected:string[];onToggle:(v:string)=>void}){return <div><p className="mb-2 text-[10px] font-black uppercase tracking-wide text-slate-500">{title}</p><div className="flex flex-wrap gap-2">{values.map(v=><button key={v} type="button" onClick={()=>onToggle(v)} className={`rounded-lg border px-2.5 py-1.5 text-[10px] font-bold ${selected.includes(v)?'border-blue-500 bg-blue-50 text-blue-700':'border-slate-200 text-slate-500'}`}>{v}</button>)}</div></div>}
