'use client';
import { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, Edit3, History, Package, Plus, Save, Settings2, Trash2, X, ArrowDownToLine, SlidersHorizontal } from 'lucide-react';
import { SERVICE_CATALOG } from '@/lib/serviceCatalog';

type Usage={serviceId:string;serviceName:string;quantity:number};
type Item={_id:string;name:string;unit:string;quantity:number;lowStockThreshold:number;costPerUnit:number;active:boolean;usage:Usage[]};
type Movement={_id:string;itemId:string;itemName:string;type:'sale'|'restock'|'adjustment'|'void'|'restore';quantity:number;beforeQuantity:number;afterQuantity:number;reason:string;createdAt:string};
const blank={name:'',unit:'pcs',lowStockThreshold:'0',costPerUnit:'0'};

export default function InventoryManager(){
 const [items,setItems]=useState<Item[]>([]),[loading,setLoading]=useState(true),[msg,setMsg]=useState(''),[form,setForm]=useState(blank),[editing,setEditing]=useState<Item|null>(null),[formOpen,setFormOpen]=useState(false),[usageItem,setUsageItem]=useState<Item|null>(null),[usage,setUsage]=useState<Usage[]>([]),[sid,setSid]=useState(''),[qty,setQty]=useState(''),[stockItem,setStockItem]=useState<Item|null>(null),[stockType,setStockType]=useState<'restock'|'adjustment'>('restock'),[stockQty,setStockQty]=useState(''),[reason,setReason]=useState(''),[stockSaving,setStockSaving]=useState(false),[historyOpen,setHistoryOpen]=useState(false),[movements,setMovements]=useState<Movement[]>([]),[historyLoading,setHistoryLoading]=useState(false),[historyFilter,setHistoryFilter]=useState('');
 const load=async()=>{try{const r=await fetch('/api/inventory',{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error);setItems(d.items||[])}catch(e){setMsg(e instanceof Error?e.message:'Unable to load inventory.')}finally{setLoading(false)}};
 useEffect(()=>{load();const t=setInterval(load,5000);return()=>clearInterval(t)},[]);
 const low=useMemo(()=>items.filter(i=>i.active&&i.quantity<=i.lowStockThreshold),[items]);
 const openAdd=()=>{setEditing(null);setForm(blank);setFormOpen(true)};
 const openEdit=(i:Item)=>{setEditing(i);setForm({name:i.name,unit:i.unit,lowStockThreshold:String(i.lowStockThreshold),costPerUnit:String(i.costPerUnit)});setFormOpen(true)};
 const save=async()=>{const body={name:form.name.trim(),unit:form.unit.trim(),lowStockThreshold:Number(form.lowStockThreshold)||0,costPerUnit:Number(form.costPerUnit)||0};if(!body.name||!body.unit){setMsg('Name and unit are required.');return}const r=await fetch('/api/inventory',{method:editing?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(editing?{id:editing._id,...body}:body)}),d=await r.json();if(!r.ok){setMsg(d.error||'Unable to save');return}setFormOpen(false);setMsg(editing?'Item updated.':'Item added.');load()};
 const deactivate=async(i:Item)=>{if(!confirm(`Deactivate ${i.name}?`))return;const r=await fetch(`/api/inventory?id=${i._id}`,{method:'DELETE'});const d=await r.json();setMsg(r.ok?`${i.name} deactivated.`:d.error||'Unable to deactivate');load()};
 const openUsage=(i:Item)=>{setUsageItem(i);setUsage(i.usage||[]);setSid('');setQty('')};
 const addUsage=()=>{const s=SERVICE_CATALOG.find(x=>x.id===sid),n=Number(qty);if(!s||!(n>0))return;setUsage(a=>a.some(x=>x.serviceId===s.id)?a.map(x=>x.serviceId===s.id?{...x,quantity:n}:x):[...a,{serviceId:s.id,serviceName:s.name,quantity:n}]);setSid('');setQty('')};
 const saveUsage=async()=>{if(!usageItem)return;const r=await fetch('/api/inventory',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:usageItem._id,usage})}),d=await r.json();if(!r.ok){setMsg(d.error||'Unable to save usage');return}setUsageItem(null);setMsg(`Consumption rules saved for ${usageItem.name}.`);load()};
 const openStock=(i:Item,type:'restock'|'adjustment')=>{setStockItem(i);setStockType(type);setStockQty('');setReason('');setMsg('')};
 const saveStock=async()=>{if(!stockItem)return;const n=Number(stockQty);if(!Number.isFinite(n)||n===0){setMsg('Enter a non-zero quantity.');return}if(stockType==='restock'&&n<0){setMsg('Restock quantity must be positive.');return}if(!reason.trim()){setMsg('A reason is required.');return}setStockSaving(true);try{const r=await fetch('/api/inventory/movements',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({itemId:stockItem._id,type:stockType,quantity:n,reason:reason.trim()})}),d=await r.json();if(!r.ok){setMsg(d.error||'Unable to update stock');return}setStockItem(null);setMsg(stockType==='restock'?`${stockItem.name} restocked.`:`${stockItem.name} adjusted.`);load();if(historyOpen)loadHistory()}finally{setStockSaving(false)}};
 const loadHistory=async()=>{setHistoryLoading(true);try{const r=await fetch('/api/inventory/movements',{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error);setMovements(d.movements||[])}catch(e){setMsg(e instanceof Error?e.message:'Unable to load history.')}finally{setHistoryLoading(false)}};
 const openHistory=()=>{setHistoryOpen(true);loadHistory()};
 const visibleMovements=useMemo(()=>historyFilter?movements.filter(m=>m.itemId===historyFilter):movements,[movements,historyFilter]);
 return <div className="h-full w-full overflow-y-auto bg-slate-50/60 p-6 text-slate-900"><div className="mx-auto max-w-7xl space-y-5">
  <header className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div><h1 className="text-lg font-black">Inventory</h1><p className="mt-1 text-xs text-slate-500">Manage stock, consumption rules, and audited stock movements.</p></div><div className="flex gap-2"><button onClick={openHistory} className="flex items-center gap-2 rounded-xl border border-slate-300 bg-white px-4 py-2.5 text-xs font-extrabold"><History className="h-4 w-4"/>Movement History</button><button onClick={openAdd} className="flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-2.5 text-xs font-extrabold text-white"><Plus className="h-4 w-4"/>Add Item</button></div></header>
  {msg&&<div className="rounded-xl border border-slate-200 bg-white px-4 py-3 text-xs font-semibold">{msg}</div>}{low.length>0&&<div className="flex items-center gap-2 rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-xs font-bold text-amber-800"><AlertTriangle className="h-4 w-4"/>{low.length} item(s) at or below low stock.</div>}
  {loading?<div className="rounded-2xl bg-white p-10 text-center text-xs font-semibold text-slate-500">Loading inventory...</div>:items.length===0?<div className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center"><Package className="mx-auto h-9 w-9 text-slate-300"/><h2 className="mt-3 text-sm font-black">No inventory items</h2><button onClick={openAdd} className="mt-4 rounded-xl bg-blue-600 px-4 py-2.5 text-xs font-extrabold text-white">Add First Item</button></div>:<div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white shadow-sm"><table className="w-full min-w-[1050px] text-left"><thead className="bg-slate-50 text-[10px] font-extrabold uppercase text-slate-600"><tr><th className="px-4 py-3">Item</th><th className="px-4 py-3">Stock</th><th className="px-4 py-3">Low Stock</th><th className="px-4 py-3">Cost / Unit</th><th className="px-4 py-3">Service Usage</th><th className="px-4 py-3">Stock Actions</th><th className="px-4 py-3 text-right">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{items.map(i=><tr key={i._id} className={!i.active?'opacity-50':''}><td className="px-4 py-4"><div className="text-xs font-extrabold">{i.name}</div><div className="text-[10px] text-slate-500">{i.unit} · {i.active?'Active':'Inactive'}</div></td><td className={`px-4 py-4 text-sm font-black ${i.active&&i.quantity<=i.lowStockThreshold?'text-amber-700':''}`}>{i.quantity.toLocaleString()} <span className="text-[10px] font-semibold text-slate-500">{i.unit}</span></td><td className="px-4 py-4 text-xs font-bold">{i.lowStockThreshold} {i.unit}</td><td className="px-4 py-4 text-xs font-bold">₱{i.costPerUnit.toLocaleString('en-PH',{minimumFractionDigits:2})}</td><td className="px-4 py-4"><button disabled={!i.active} onClick={()=>openUsage(i)} className="rounded-lg border border-slate-300 px-3 py-2 text-[10px] font-extrabold disabled:opacity-50"><Settings2 className="mr-1 inline h-3 w-3"/>{i.usage?.length||0} configured</button></td><td className="px-4 py-4"><div className="flex gap-2"><button disabled={!i.active} onClick={()=>openStock(i,'restock')} className="rounded-lg border border-slate-300 px-3 py-2 text-[10px] font-extrabold disabled:opacity-50"><ArrowDownToLine className="mr-1 inline h-3 w-3"/>Restock</button><button disabled={!i.active} onClick={()=>openStock(i,'adjustment')} className="rounded-lg border border-slate-300 px-3 py-2 text-[10px] font-extrabold disabled:opacity-50"><SlidersHorizontal className="mr-1 inline h-3 w-3"/>Adjust</button></div></td><td className="px-4 py-4"><div className="flex justify-end gap-2"><button onClick={()=>openEdit(i)} className="rounded-lg border border-slate-300 p-2"><Edit3 className="h-3.5 w-3.5"/></button>{i.active&&<button onClick={()=>deactivate(i)} className="rounded-lg border border-slate-300 p-2 text-red-600"><Trash2 className="h-3.5 w-3.5"/></button>}</div></td></tr>)}</tbody></table></div>}
 </div>
 {formOpen&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4"><div className="w-full max-w-lg rounded-2xl bg-white p-5 shadow-2xl"><div className="flex justify-between"><div><h2 className="text-sm font-black">{editing?'Edit':'Add'} Inventory Item</h2><p className="mt-1 text-[11px] text-slate-500">Stock quantity is changed through audited stock movements.</p></div><button onClick={()=>setFormOpen(false)}><X/></button></div><div className="mt-5 grid grid-cols-2 gap-3">{(['name','unit','lowStockThreshold','costPerUnit'] as const).map(k=><label key={k} className={k==='name'?'col-span-2':''}><span className="mb-1 block text-[10px] font-extrabold uppercase text-slate-600">{k==='lowStockThreshold'?'Low-stock threshold':k==='costPerUnit'?'Cost per unit':k}</span><input value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})} type={k==='name'||k==='unit'?'text':'number'} min={k==='name'||k==='unit'?undefined:0} step={k==='name'||k==='unit'?undefined:'any'} className="w-full rounded-lg border border-slate-300 px-3 py-2.5 text-xs font-semibold"/></label>)}</div><button onClick={save} className="mt-5 flex w-full justify-center gap-2 rounded-xl bg-blue-600 py-3 text-xs font-extrabold text-white"><Save className="h-4 w-4"/>Save Item</button></div></div>}
 {stockItem&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4"><div className="w-full max-w-md rounded-2xl bg-white p-5 shadow-2xl"><div className="flex justify-between"><div><h2 className="text-sm font-black">{stockType==='restock'?'Restock Inventory':'Adjust Inventory'}</h2><p className="mt-1 text-[11px] text-slate-500">{stockItem.name} · Current stock: <b>{stockItem.quantity} {stockItem.unit}</b></p></div><button onClick={()=>setStockItem(null)}><X/></button></div><div className="mt-5 space-y-3"><label><span className="mb-1 block text-[10px] font-extrabold uppercase text-slate-600">Quantity {stockType==='adjustment'?'(+ add / − remove)':''}</span><input autoFocus value={stockQty} onChange={e=>setStockQty(e.target.value)} type="number" step="any" placeholder={stockItem.unit} className="w-full rounded-lg border border-slate-300 px-3 py-2.5 text-xs font-semibold"/></label><label><span className="mb-1 block text-[10px] font-extrabold uppercase text-slate-600">Reason</span><textarea value={reason} onChange={e=>setReason(e.target.value)} rows={3} placeholder={stockType==='restock'?'e.g. New supplier delivery':'e.g. Physical stock count correction'} className="w-full rounded-lg border border-slate-300 px-3 py-2.5 text-xs font-semibold"/></label><button disabled={stockSaving} onClick={saveStock} className="flex w-full justify-center gap-2 rounded-xl bg-blue-600 py-3 text-xs font-extrabold text-white disabled:opacity-50"><Save className="h-4 w-4"/>{stockSaving?'Saving...':'Save Movement'}</button></div></div></div>}
 {usageItem&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4"><div className="w-full max-w-2xl rounded-2xl bg-white p-5 shadow-2xl"><div className="flex justify-between"><div><h2 className="text-sm font-black">Service Consumption</h2><p className="mt-1 text-[11px] text-slate-500">How much <b>{usageItem.name}</b> each service uses.</p></div><button onClick={()=>setUsageItem(null)}><X/></button></div><div className="mt-5 grid grid-cols-[1fr_120px_auto] gap-2"><select value={sid} onChange={e=>setSid(e.target.value)} className="rounded-lg border border-slate-300 px-3 py-2 text-xs font-semibold"><option value="">Select service/package...</option>{SERVICE_CATALOG.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><input value={qty} onChange={e=>setQty(e.target.value)} type="number" min="0" step="any" placeholder={usageItem.unit} className="rounded-lg border border-slate-300 px-3 py-2 text-xs"/><button onClick={addUsage} disabled={!sid||!(Number(qty)>0)} className="rounded-lg bg-blue-600 px-3 text-[10px] font-extrabold text-white disabled:bg-slate-300">Add</button></div><div className="mt-4 max-h-80 overflow-y-auto rounded-xl border border-slate-200">{usage.length===0?<div className="p-8 text-center text-xs text-slate-500">No consumption rules configured.</div>:usage.map((u,n)=><div key={u.serviceId} className="grid grid-cols-[1fr_120px_auto] items-center gap-2 border-b border-slate-100 p-3"><div className="text-xs font-bold">{u.serviceName}</div><input value={u.quantity} onChange={e=>setUsage(a=>a.map((x,j)=>j===n?{...x,quantity:Number(e.target.value)||0}:x))} type="number" min="0" step="any" className="rounded-lg border border-slate-300 px-2 py-1.5 text-xs"/><button onClick={()=>setUsage(a=>a.filter((_,j)=>j!==n))} className="p-2 text-red-600"><Trash2 className="h-3.5 w-3.5"/></button></div>)}</div><button onClick={saveUsage} className="mt-5 flex w-full justify-center gap-2 rounded-xl bg-blue-600 py-3 text-xs font-extrabold text-white"><Save className="h-4 w-4"/>Save Consumption Rules</button></div></div>}
 {historyOpen&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4"><div className="flex max-h-[85vh] w-full max-w-5xl flex-col rounded-2xl bg-white shadow-2xl"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-200 p-5"><div><h2 className="text-sm font-black">Inventory Movement History</h2><p className="mt-1 text-[11px] text-slate-500">Sales, restocks, adjustments, voids, and restores.</p></div><div className="flex items-center gap-2"><select value={historyFilter} onChange={e=>setHistoryFilter(e.target.value)} className="rounded-lg border border-slate-300 px-3 py-2 text-xs font-semibold"><option value="">All items</option>{items.map(i=><option key={i._id} value={i._id}>{i.name}</option>)}</select><button onClick={()=>setHistoryOpen(false)}><X/></button></div></div><div className="overflow-auto p-4">{historyLoading?<div className="p-10 text-center text-xs text-slate-500">Loading history...</div>:visibleMovements.length===0?<div className="p-10 text-center text-xs text-slate-500">No inventory movements recorded.</div>:<table className="w-full min-w-[850px] text-left"><thead className="text-[10px] font-extrabold uppercase text-slate-500"><tr><th className="px-3 py-3">Date</th><th className="px-3 py-3">Item</th><th className="px-3 py-3">Type</th><th className="px-3 py-3">Change</th><th className="px-3 py-3">Stock</th><th className="px-3 py-3">Reason</th></tr></thead><tbody className="divide-y divide-slate-100">{visibleMovements.map(m=><tr key={m._id}><td className="px-3 py-3 text-[10px] text-slate-500">{new Date(m.createdAt).toLocaleString()}</td><td className="px-3 py-3 text-xs font-bold">{m.itemName}</td><td className="px-3 py-3 text-[10px] font-extrabold uppercase">{m.type}</td><td className={`px-3 py-3 text-xs font-black ${m.quantity<0?'text-red-600':'text-emerald-700'}`}>{m.quantity>0?'+':''}{m.quantity}</td><td className="px-3 py-3 text-xs font-bold">{m.beforeQuantity} → {m.afterQuantity}</td><td className="px-3 py-3 text-xs text-slate-600">{m.reason}</td></tr>)}</tbody></table>}</div></div></div>}
 </div>
}
